// Code generated by protoc-gen-go.
// source: test.proto
// DO NOT EDIT!

/*
Package test is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	SDP
	ServerRequest
*/
package test

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ServerRequest_Commands int32

const (
	ServerRequest_CreateEndPoint   ServerRequest_Commands = 1
	ServerRequest_CreateVideoMix   ServerRequest_Commands = 2
	ServerRequest_AttachEndPoint   ServerRequest_Commands = 3
	ServerRequest_DeattachEndPoint ServerRequest_Commands = 4
)

var ServerRequest_Commands_name = map[int32]string{
	1: "CreateEndPoint",
	2: "CreateVideoMix",
	3: "AttachEndPoint",
	4: "DeattachEndPoint",
}
var ServerRequest_Commands_value = map[string]int32{
	"CreateEndPoint":   1,
	"CreateVideoMix":   2,
	"AttachEndPoint":   3,
	"DeattachEndPoint": 4,
}

func (x ServerRequest_Commands) Enum() *ServerRequest_Commands {
	p := new(ServerRequest_Commands)
	*p = x
	return p
}
func (x ServerRequest_Commands) String() string {
	return proto.EnumName(ServerRequest_Commands_name, int32(x))
}
func (x *ServerRequest_Commands) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ServerRequest_Commands_value, data, "ServerRequest_Commands")
	if err != nil {
		return err
	}
	*x = ServerRequest_Commands(value)
	return nil
}

type SDP struct {
	V                *string `protobuf:"bytes,1,req,name=v" json:"v,omitempty"`
	O                *string `protobuf:"bytes,2,req,name=o" json:"o,omitempty"`
	C                *string `protobuf:"bytes,3,req,name=c" json:"c,omitempty"`
	M                *string `protobuf:"bytes,4,req,name=m" json:"m,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SDP) Reset()         { *m = SDP{} }
func (m *SDP) String() string { return proto.CompactTextString(m) }
func (*SDP) ProtoMessage()    {}

func (m *SDP) GetV() string {
	if m != nil && m.V != nil {
		return *m.V
	}
	return ""
}

func (m *SDP) GetO() string {
	if m != nil && m.O != nil {
		return *m.O
	}
	return ""
}

func (m *SDP) GetC() string {
	if m != nil && m.C != nil {
		return *m.C
	}
	return ""
}

func (m *SDP) GetM() string {
	if m != nil && m.M != nil {
		return *m.M
	}
	return ""
}

type ServerRequest struct {
	Command          *ServerRequest_Commands `protobuf:"varint,1,req,enum=test.ServerRequest_Commands" json:"Command,omitempty"`
	Sdp              *SDP                    `protobuf:"bytes,2,opt,name=sdp" json:"sdp,omitempty"`
	Params           []string                `protobuf:"bytes,3,rep" json:"Params,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *ServerRequest) Reset()         { *m = ServerRequest{} }
func (m *ServerRequest) String() string { return proto.CompactTextString(m) }
func (*ServerRequest) ProtoMessage()    {}

func (m *ServerRequest) GetCommand() ServerRequest_Commands {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return ServerRequest_CreateEndPoint
}

func (m *ServerRequest) GetSdp() *SDP {
	if m != nil {
		return m.Sdp
	}
	return nil
}

func (m *ServerRequest) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterEnum("test.ServerRequest_Commands", ServerRequest_Commands_name, ServerRequest_Commands_value)
}
